config/routes.rb
Rails.application.routes.draw do
  resources :users do
    post :clock_out, to: 'clock_in_outs#clock_out'
    post :clock_in, to: 'clock_in_outs#clock_in'

    get :clocks, to: 'clock_in_outs#index'
    get :following_user_clocks, to: 'clock_in_outs#following_user_clocks'
    delete :unfollow, to: 'follows#unfollow'
    resources :follows
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/clock_in_out.rb
class ClockInOut < ApplicationRecord
  belongs_to :user

  validates :user, presence: true
  validates :clock_in, presence: true
  validate :should_be_clocked_once
  # validates :clock_out, presence: true, :if => Proc.new { |clockinout | clockinout clockinout.clock_in.present? }


  def should_be_clocked_once
    if clock_in_changed? && clock_in_was != nil
      errors.add(:clock_in_change, 'Cannot update clock in')
    end

    if clock_out_changed? && clock_out_was != nil
      errors.add(:clock_out_change, 'Cannot update clock out')
    end
  end

  def self.clock_in(user_id)
    now = DateTime.now
    clock_in_out = self.find_or_create_by(user_id: user_id, target_date: now.to_date)
    clock_in_out.clock_in = now
    clock_in_out.save
    clock_in_out
  end

  def self.clock_out(user_id)
    now = DateTime.now
    clock_in_out = self.find_or_create_by(user_id: user_id, target_date: now.to_date)
    duration = now.to_i - clock_in_out.clock_in.to_i
    clock_in_out.clock_out = now
    clock_in_out.duration = duration
    clock_in_out.save
    clock_in_out
  end

  def self.find_by_user_ordered_created_at(user_id)
    self.where(user_id: user_id).order(created_at: :desc)
  end
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User', foreign_key: 'follower_id'
  belongs_to :followed, class_name: 'User', foreign_key: 'followed_id'

  validates_uniqueness_of :follower_id, scope: :followed_id
end

app/models/user.rb
class User < ApplicationRecord
  has_many :followings, class_name: 'Follow', foreign_key: 'follower_id'
  has_many :followers, class_name: 'Follow', foreign_key: 'followed_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token

  private
  def set_default_page
    @page = params[:page] || 1
    @per_page = params[:per_page] || 10
  end
end

app/controllers/clock_in_outs_controller.rb
class ClockInOutsController < ApplicationController
  before_action :set_clock_in_out, only: %i[ show edit update destroy ]
  before_action :set_user
  before_action :set_default_page, only: %i[ index following_user_clocks ]

  # GET /clock_in_outs or /clock_in_outs.json
  def index
    @clock_in_outs = ClockInOut.find_by_user_ordered_created_at(@user.id).page(@page).per(@per_page)
    respond_to do |format|
      format.json { render json: @clock_in_outs, status: 200 }
    end
  end

  def following_user_clocks
    @clock_in_outs = ClockInOut.
      joins(:user => :followers).
      where(user: { follows: { follower_id: @user.id } }, clock_in: (Date.today - 1.week)..Date.today).
      order(duration: :desc).
      page(@page).
      per(@per_page)

    respond_to do |format|
      format.json { render json: @clock_in_outs, status: 200 }
    end
  end

  def clock_in
    @record = ClockInOut.clock_in(@user.id)
    respond_to do |format|
      if @record.errors.empty?
        format.json { render json: @record, status: :ok }
      else
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
    return
  end

  def clock_out
    @record = ClockInOut.clock_out(@user.id)
    respond_to do |format|
      if @record.errors.empty?
        format.json { render json: @record, status: :ok }
      else
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clock_in_out
      @clock_in_out = ClockInOut.find(params[:id])
    end

    def set_user
      if params[:user_id].present?
        @user = User.find params[:user_id]
      else
          raise ArgumentError, "Undefined user or ID #{params[:user_id]}"
      end
    end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :set_follow, only: %i[ show edit update destroy ]
  before_action :set_default_page, only: %i[ index ]

  # GET /follows or /follows.json
  def followings
    @follows = Follow.where(follower_id: params[:user_id]).page(@page).per(@page)
    respond_to do |format|
      format.json { render json: @follows }
    end
  end

  def followers
    @follows = Follow.where(followed_id: params[:user_id]).page(@page).per(@page)
    respond_to do |format|
      format.json { render json: @follows }
    end
  end

  # GET /follows/1 or /follows/1.json
  def show
    @follow = Follow.where(id: params[:id], follower_id: params[:user_id])
    respond_to do |format|
      format.json { render json: @follow }
    end
  end

  # POST /follows or /follows.json
  def create
    @follow = Follow.new(follow_params)

    respond_to do |format|
      if @follow.save
        format.json { render json: @follow, status: :created }
      else
        format.json { render json: @follow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /follows/1 or /follows/1.json
  def destroy
    @follow.destroy

    respond_to do |format|
      format.html { redirect_to follows_path, status: :see_other, notice: "Follow was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def unfollow
    if params[:followed_id].blank?
      raise ArgumentError, "undefined followed_id"
    end

    follow = Follow.where(follower_id: params[:user_id], followed_id: params[:followed_id]).first
    if follow.present?
      if follow.destroy
        respond_to do |format|
          format.json { head :no_content }
        end
      else
        respond_to do |format|
          format.json { render json: @follow.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.json { render json: "Cannot perform action, already unfollowed", status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_follow
      @follow = Follow.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def follow_params
      params.require(:follow).permit(:follower_id, :followed_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :set_default_page, only: %i[ index ]

  # GET /users or /users.json
  def index
    @users = User.all.page(@page).per_page(@per_page)

    respond_to do |format|
      format.json { render json: @users, status: :ok }
    end
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.json { render :show, status: :created, location: @user }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
    return
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.json { render :show, status: :ok, location: @user }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clock_in_outs_helper.rb
module ClockInOutsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clock_in_outs/_clock_in_out.html.erb
<div id="<%= dom_id clock_in_out %>">
  <p>
    <strong>Target date:</strong>
    <%= clock_in_out.target_date %>
  </p>

  <p>
    <strong>Clock in:</strong>
    <%= clock_in_out.clock_in %>
  </p>

  <p>
    <strong>Clock out:</strong>
    <%= clock_in_out.clock_out %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= clock_in_out.duration %>
  </p>

  <p>
    <strong>User:</strong>
    <%= clock_in_out.user_id %>
  </p>

</div>

app/views/clock_in_outs/_form.html.erb
<%= form_with(model: clock_in_out) do |form| %>
  <% if clock_in_out.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(clock_in_out.errors.count, "error") %> prohibited this clock_in_out from being saved:</h2>

      <ul>
        <% clock_in_out.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :target_date, style: "display: block" %>
    <%= form.date_field :target_date %>
  </div>

  <div>
    <%= form.label :clock_in, style: "display: block" %>
    <%= form.datetime_field :clock_in %>
  </div>

  <div>
    <%= form.label :clock_out, style: "display: block" %>
    <%= form.datetime_field :clock_out %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clock_in_outs/edit.html.erb
<h1>Editing clock in out</h1>

<%= render "form", clock_in_out: @clock_in_out %>

<br>

<div>
  <%= link_to "Show this clock in out", @clock_in_out %> |
  <%= link_to "Back to clock in outs", clock_in_outs_path %>
</div>

app/views/clock_in_outs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clock in outs</h1>

<div id="clock_in_outs">
  <% @clock_in_outs.each do |clock_in_out| %>
    <%= render clock_in_out %>
    <p>
      <%= link_to "Show this clock in out", clock_in_out %>
    </p>
  <% end %>
</div>

<%= link_to "New clock in out", new_clock_in_out_path %>

app/views/clock_in_outs/new.html.erb
<h1>New clock in out</h1>

<%= render "form", clock_in_out: @clock_in_out %>

<br>

<div>
  <%= link_to "Back to clock in outs", clock_in_outs_path %>
</div>

app/views/clock_in_outs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @clock_in_out %>

<div>
  <%= link_to "Edit this clock in out", edit_clock_in_out_path(@clock_in_out) %> |
  <%= link_to "Back to clock in outs", clock_in_outs_path %>

  <%= button_to "Destroy this clock in out", @clock_in_out, method: :delete %>
</div>

app/views/follows/_follow.html.erb
<div id="<%= dom_id follow %>">
  <p>
    <strong>Follower:</strong>
    <%= follow.follower_id %>
  </p>

  <p>
    <strong>Followed:</strong>
    <%= follow.followed_id %>
  </p>

</div>

app/views/follows/_form.html.erb
<%= form_with(model: follow) do |form| %>
  <% if follow.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(follow.errors.count, "error") %> prohibited this follow from being saved:</h2>

      <ul>
        <% follow.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :follower_id, style: "display: block" %>
    <%= form.text_field :follower_id %>
  </div>

  <div>
    <%= form.label :followed_id, style: "display: block" %>
    <%= form.text_field :followed_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/follows/edit.html.erb
<h1>Editing follow</h1>

<%= render "form", follow: @follow %>

<br>

<div>
  <%= link_to "Show this follow", @follow %> |
  <%= link_to "Back to follows", follows_path %>
</div>

app/views/follows/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Follows</h1>

<div id="follows">
  <% @follows.each do |follow| %>
    <%= render follow %>
    <p>
      <%= link_to "Show this follow", follow %>
    </p>
  <% end %>
</div>

<%= link_to "New follow", new_follow_path %>

app/views/follows/new.html.erb
<h1>New follow</h1>

<%= render "form", follow: @follow %>

<br>

<div>
  <%= link_to "Back to follows", follows_path %>
</div>

app/views/follows/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @follow %>

<div>
  <%= link_to "Edit this follow", edit_follow_path(@follow) %> |
  <%= link_to "Back to follows", follows_path %>

  <%= button_to "Destroy this follow", @follow, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sleepy2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>